"use client";
import Link from "next/link"; import { usePathname } from "next/navigation";
import { BarChart3, Bot, ChevronDown, Contact, LayoutDashboard, ListTodo, Megaphone, Menu, Phone, PieChart, Settings, Target, Users } from "lucide-react";
import { useState } from "react"; import { useAuth } from "@/features/auth/auth-provider"; import { cn } from "@/lib/utils";
const nav = [["Dashboard","/dashboard",LayoutDashboard],["Calls","/calls",Phone],["Contacts","/contacts",Contact],["Follow-ups","/follow-ups",ListTodo],["Leads","/leads",Target],["Agents","/agents",Bot],["Teams","/teams",Users],["Campaigns","/campaigns",Megaphone],["Analytics","/analytics",BarChart3],["Reports","/reports",PieChart]] as const;
export function AppShell({ children }: { children: React.ReactNode }) {
 const path=usePathname(); const {user,signOut}=useAuth(); const [mobile,setMobile]=useState(false); const [menu,setMenu]=useState(false);
 const side=<><div className="flex h-16 items-center gap-3 px-5 text-lg font-semibold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-primary text-white">CP</span>Careergize Pulse</div><nav className="flex-1 space-y-1 px-3 py-4">{nav.map(([label,href,Icon])=><Link key={href} href={href} onClick={()=>setMobile(false)} className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-slate-600 hover:bg-slate-100",path===href&&"bg-blue-50 text-primary")}><Icon size={18}/>{label}</Link>)}</nav><div className="border-t p-3"><Link href="/settings/general" className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-slate-600",path.startsWith("/settings")&&"bg-blue-50 text-primary")}><Settings size={18}/>Settings</Link></div></>;
 return <div className="min-h-screen bg-slate-50"><aside className="fixed inset-y-0 left-0 hidden w-64 flex-col border-r bg-white lg:flex">{side}</aside>{mobile&&<div className="fixed inset-0 z-40 bg-black/40 lg:hidden" onClick={()=>setMobile(false)}><aside className="h-full w-64 bg-white" onClick={e=>e.stopPropagation()}>{side}</aside></div>}<div className="lg:pl-64"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b bg-white/95 px-4 backdrop-blur sm:px-6"><button className="lg:hidden" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu/></button><div className="hidden text-sm text-muted-foreground sm:block">{user?.organization_detail?.name}</div><div className="relative"><button onClick={()=>setMenu(!menu)} className="flex items-center gap-3 rounded-lg p-1.5 hover:bg-slate-100"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-900 text-xs font-semibold text-white">{user?.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><span className="hidden text-left sm:block"><span className="block text-sm font-medium">{user?.name}</span><span className="block text-xs capitalize text-muted-foreground">{user?.role.replaceAll("_"," ")}</span></span><ChevronDown size={16}/></button>{menu&&<div className="absolute right-0 mt-2 w-48 rounded-lg border bg-white p-1 shadow-lg"><Link href="/settings/general" className="block rounded px-3 py-2 text-sm hover:bg-slate-50">Account settings</Link><button onClick={signOut} className="w-full rounded px-3 py-2 text-left text-sm text-red-600 hover:bg-red-50">Sign out</button></div>}</div></header><main className="p-4 sm:p-6 lg:p-8">{children}</main></div></div>;
}
