# Generated by Django 5.1.7 on 2026-08-25 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0002_initial'),
        ('contacts', '0001_initial'),
        ('organizations', '0002_default_organization'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='call',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='call',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='teams.team'),
        ),
        migrations.AddField(
            model_name='callevent',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calls.call'),
        ),
        migrations.AddField(
            model_name='callevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='callnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callnote',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='calls.call'),
        ),
        migrations.AddField(
            model_name='callnote',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='calloutcome',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='call',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='calls.calloutcome'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_numbers', to='teams.team'),
        ),
        migrations.AddField(
            model_name='call',
            name='tracked_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='calls.phonenumber'),
        ),
        migrations.AddIndex(
            model_name='callevent',
            index=models.Index(fields=['organization', 'call', 'timestamp'], name='calls_calle_organiz_107027_idx'),
        ),
        migrations.AddConstraint(
            model_name='callevent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('organization', 'provider_event_id'), name='unique_call_event_provider_id_per_org'),
        ),
        migrations.AddIndex(
            model_name='callnote',
            index=models.Index(fields=['organization', 'call', 'created_at'], name='calls_calln_organiz_cff32d_idx'),
        ),
        migrations.AddConstraint(
            model_name='calloutcome',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_call_outcome_per_org'),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='unique_phone_number_per_org'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['organization', 'started_at'], name='calls_call_organiz_368c29_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['organization', 'status', 'started_at'], name='calls_call_organiz_314bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['organization', 'caller_number'], name='calls_call_organiz_1162d8_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['organization', 'receiver_number'], name='calls_call_organiz_870756_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['organization', 'agent', 'started_at'], name='calls_call_organiz_2321a3_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['organization', 'campaign', 'started_at'], name='calls_call_organiz_494180_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['organization', 'provider_call_id'], name='calls_call_organiz_88001c_idx'),
        ),
        migrations.AddConstraint(
            model_name='call',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_call_id', ''), _negated=True), fields=('organization', 'provider', 'provider_call_id'), name='unique_provider_call_per_org'),
        ),
    ]
